// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRf0RX7MmKhGDk-SQlKpOT9PjCMZaRUI',
    appId: '1:583699680543:android:3efd66dda3d039c9d0b42a',
    messagingSenderId: '583699680543',
    projectId: 'dulashop-5e6f0',
    storageBucket: 'dulashop-5e6f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRDH1MRgmN1eWyZnnJSFZ45Xmi9N2s0qE',
    appId: '1:583699680543:ios:781af33db2dc072ad0b42a',
    messagingSenderId: '583699680543',
    projectId: 'dulashop-5e6f0',
    storageBucket: 'dulashop-5e6f0.appspot.com',
    androidClientId: '583699680543-6j7l9cedcf9fr6b81rb1idkge1m22f01.apps.googleusercontent.com',
    iosClientId: '583699680543-tftvtmc7ja8lvi0sbddca6trqfujccbm.apps.googleusercontent.com',
    iosBundleId: 'kz.bismo.app.bismo',
  );

}